# allows Vault currency be added as an asset, withdrawn or deposited to your account
vault-support: true

# allows PlayerPoints currency be added as an asset, withdrawn or deposited to your account
player-points-support: true

colors: # Allows customization of command outputs and graphs
  # Color for prices going up (hex)
  bullish: "#8CD740"

  # Color for prices going down (hex)
  bearish: "#FA413B"

database:
  # orders are able to transact across worlds if false
  data-per-world: false

  # (0)-SQLite (1)-mySQL
  database-type: 0

  mysql:
    host:
    port:
    database:
    username:
    password:
    options: "?useSSL=true&requireSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true"

exchange:
  fees: # Fixed: 23    Percentage: 23%
    # Fees when you take money from your wallet
    withdrawal-fees: 1%
    # Fees when you add money to your wallet
    deposit-fees: 2%

  commodities:
    fees: # Fixed: 23    Percentage: 23%
      # Fees when you transact immediately with another order
      taker-fees: 0
      # Fees when you add an order to the order book
      maker-fees: 0

      # Fees when you use the claiming tag on an entity (fixed only)
      entity-claiming-fees: 0

    # note: commodities are RAW and FUNGIBLE materials traded in BULK that are then processed into different products
    #       crops and building material can be commodities as well:
    #
    #       IRON IS a commodity (in real life)
    #             -All bars are the same quality, therefore interchangeable (Fungible) v
    #             -Traded in large amounts (Traded in Bulk) v
    #             -Usually gathered from the ground (raw material) v
    #
    #       DIAMOND HELMET is NOT a commodity
    #             -Enchantments, damage, and trims make each one unique (Non-Fungible) x
    #             -Usually traded one at a time (not in bulk) x
    #             -Finished product (not raw) x
    #
    #     but this is only a recommendation anyway, use this plugin however you want.
    #
    generation:
      # Allows auto-generation of assets for commodities in each world using whitelisting/blacklisting
      active: true

      # Enables whitelist and disables blacklist for items
      item-whitelisting: true
      commodity-item-whitelist:
        - COAL
        - CHARCOAL
        - IRON_INGOT
        - COPPER_INGOT
        - GOLD_INGOT
        - NETHERITE_SCRAP
        - AMETHYST_SHARD
        - DIAMOND
        - NETHER_QUARTZ
        - EMERALD
        - LAPIS_LAZULI
        - GLOWSTONE_DUST
        - REDSTONE
        - WHEAT
        - EGG
        - APPLE
        - MELON_SLICE
        - PUMPKIN
        - SWEET_BERRIES
        - GLOW_BERRIES
        - CHORUS_FRUIT
        - CARROT
        - POTATO
        - POISONOUS_POTATO
        - BEETROOT
        - FISH
        - RAW_COD
        - RAW_SALMON
        - TROPICAL_FISH
        - PUFFERFISH
        - SUGARCANE
        - KELP
        - COCOA_BEANS
        - HONEY_BOTTLE
        - SPIDER_EYE
        - ROTTEN_FLESH
        - FLINT
        - BONE
        - STRING
        - FEATHER
        - LEATHER
        - HONEYCOMB
        - INK_SAC
        - GLOW_INK_SAC
        - TURTLE_SCUTE
        - ARMADILLO_SCUTE
        - SLIME_BALL
        - CLAY_BALL
        - PRISMARINE_SHARD
        - PRISMARINE_CRYSTALS
        - NAUTILUS_SHELL
        - HEART_OF_THE_SEA
        - BLAZE_ROD
        - BREEZE_ROD
        - HEAVY_CORE
        - NETHER_STAR
        - ENDER_PEARL
        - SHULKER_SHELL
        - ECHO_SHARD
        - NETHER_WART
        - GUNPOWDER
        - DRAGON_BREATH
        - GHAST_TEAR
        - PHANTOM_MEMBRANE
        - BAMBOO
        - CACTUS
        - POWDER_SNOW_BUCKET
        - INK_SAC
        - WATER_BUCKET
        - MILK_BUCKET
        - LAVA_BUCKET
        - OAK_LOG
        - SPRUCE_LOG
        - BIRCH_LOG
        - JUNGLE_LOG
        - ACACIA_LOG
        - DARK_OAK_LOG
        - MANGROVE_LOG
        - CHERRY_LOG
        - CRIMSON_STEM
        - WARPED_STEM
        - DIRT
        - GRAVEL
        - SAND
        - COBBLESTONE
        - GRANITE
        - DIORITE
        - ANDESITE
        - OBSIDIAN
        - NETHERRACK
        - SPONGE
        - SOUL_SAND
        - SOUL_SOIL
        - ICE
        - END_STONE
        - TOTEM_OF_UNDYING
        - BROWN_MUSHROOM
        - RED_MUSHROOM

      commodity-item-blacklist:
        - BARRIER
        - COMMAND_BLOCK
        - STRUCTURE_BLOCK
        - STRUCTURE_VOID

      # Enables whitelist and disables blacklist for items
      entity-whitelisting: true
      commodity-entity-whitelist:
        - PIG
        - SHEEP
        - COW
        - CHICKEN
        - MOOSHROOM
        - VILLAGER

      # withers can be used for mining... imagine trading withers... hmmm....
      commodity-entity-blacklist:
        - ENDER_DRAGON
        - WARDEN

  forex:
    fees: # Fixed: 23    Percentage: 23%
      # Fees when you transact immediately with another order
      taker-fees: 0
      # Fees when you add an order to the order book
      maker-fees: 0

main-currency: # setting for the currency used to trade on the exchange (This can be changed in game)

  # Sets Main currency to a currency with matching code
  # If no match is found, the asset will be created using values below
  currency: EMD_Villager Emerald_#00ff00
  #
  #           <code>_<name>_<hex color>
  #
  # Example: EMD_Villager Emerald_#21ff59   (use this if you want it to look good even if it's not found)
  # Example: USD_US dollars                 (use if you want a random color)
  # Example: EUR                            (use this is you are really sure currency already exists)
  #
  # creation:
  # 3-letter codes only, example: USD ---> you have: 89.32 USD !!
  # Name, color and description are optional. (color is selected at random) (name uses code)


  # When true, if no match is found a hook currency will take its place, or create if no hooks are found
  # hooks: Vault (VLT), Player Points (PTS)
  create-last-resort-only: true

  # Initial amount of Main Currency that new players will have on their wallets by default (other than 0 may devalue your currency, use only for initial supply)
  initial-balance: 0

  # currency that will be deposited or withdrawn for every hook
  vault-currency: VLT_Vault Currency_#ffbb15
  playerpoints-currency: PTS_Player Points_#ff6d92